package com.example.model

enum class Language(val code: String, val displayName: String) {
    BANGLA("bn", "বাংলা"),
    ENGLISH("en", "English")
}

object AppStrings {
    fun get(key: String, lang: Language): String {
        val strings = if (lang == Language.BANGLA) bnStrings else enStrings
        return strings[key] ?: enStrings[key] ?: key
    }

    private val enStrings = mapOf(
        "app_title" to "Siam Shop",
        "app_name" to "Siam Shop",
        "delivery_address" to "Delivery Address",
        "add_address" to "Add Address",
        "saved_addresses" to "Saved Addresses",
        "order_number" to "Order #",
        "track_order" to "Track Order",
        "order_summary" to "Order Summary",
        "account" to "Account",
        "tagline" to "Your Trusted Modern Marketplace",
        "search_hint" to "Search 10,000+ products, brands...",
        "all_categories" to "All Categories",
        "flash_sale" to "⚡ Flash Deals",
        "popular_products" to "Popular Products",
        "new_arrivals" to "New Arrivals",
        "best_sellers" to "Best Sellers",
        "view_all" to "View All",
        "add_to_cart" to "Add to Cart",
        "buy_now" to "Buy Now",
        "in_stock" to "In Stock",
        "out_of_stock" to "Out of Stock",
        "stock_left" to "units available",
        "reviews" to "Reviews",
        "specifications" to "Specifications",
        "seller_info" to "Sold by",
        "delivery_free" to "Free Delivery over ৳1,000",
        "return_policy" to "7 Days Easy Return Guarantee",
        "warranty" to "100% Authentic Product",
        "cart_title" to "Shopping Cart",
        "cart_empty" to "Your cart is empty",
        "cart_empty_sub" to "Explore our categories and find great deals!",
        "start_shopping" to "Start Shopping",
        "subtotal" to "Subtotal",
        "discount" to "Discount",
        "delivery_fee" to "Delivery Fee",
        "total" to "Total Amount",
        "checkout" to "Proceed to Checkout",
        "apply_coupon" to "Apply Coupon",
        "coupon_code" to "Enter coupon code (e.g. SIAM10)",
        "coupon_applied" to "Coupon applied successfully!",
        "coupon_invalid" to "Invalid coupon code",
        "shipping_address" to "Shipping Address",
        "select_address" to "Select Delivery Address",
        "add_new_address" to "+ Add New Address",
        "payment_method" to "Payment Method",
        "place_order" to "Place Order",
        "order_success" to "Order Placed Successfully!",
        "order_success_sub" to "Thank you for shopping at Siam Shop. Track your order status in real-time.",
        "order_tracking" to "Track Order",
        "order_history" to "Order History",
        "no_orders" to "No orders found",
        "wishlist" to "My Wishlist",
        "wishlist_empty" to "Your wishlist is empty",
        "notifications" to "Notifications",
        "profile" to "My Account",
        "switch_role" to "Switch Active Mode",
        "role_customer" to "Customer View",
        "role_seller" to "Seller Partner Panel",
        "role_admin" to "Admin Dashboard",
        "admin_dashboard" to "Siam Shop Admin",
        "seller_dashboard" to "Seller Partner Dashboard",
        "products_management" to "Products",
        "categories_management" to "Categories",
        "orders_management" to "Orders",
        "coupons_management" to "Coupons",
        "sellers_management" to "Sellers",
        "sales_report" to "Sales Analytics",
        "banners_management" to "Banners & Promos",
        "total_revenue" to "Total Revenue",
        "total_orders" to "Total Orders",
        "active_sellers" to "Active Sellers",
        "total_products" to "Total Products",
        "add_product" to "+ Add New Product",
        "add_category" to "+ Add Category",
        "add_coupon" to "+ Add Coupon",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "language_toggle" to "Language / ভাষা",
        "currency_symbol" to "৳",
        "taka" to "BDT"
    )

    private val bnStrings = mapOf(
        "app_title" to "সিয়াম শপ",
        "app_name" to "সিয়াম শপ",
        "delivery_address" to "ডেলিভারি ঠিকানা",
        "add_address" to "ঠিকানা যোগ করুন",
        "saved_addresses" to "সংরক্ষিত ঠিকানা সমূহ",
        "order_number" to "অর্ডার নম্বর",
        "track_order" to "অর্ডার ট্র্যাকিং",
        "order_summary" to "অর্ডার সারাংশ",
        "account" to "অ্যাকাউন্ট",
        "tagline" to "আপনার বিশ্বস্ত আধুনিক মার্কেটপ্লেস",
        "search_hint" to "১০,০০০+ পণ্য ও ব্র্যান্ড খুঁজুন...",
        "all_categories" to "সকল ক্যাটাগরি",
        "flash_sale" to "⚡ ফ্ল্যাশ সেল",
        "popular_products" to "জনপ্রিয় পণ্য",
        "new_arrivals" to "নতুন কালেকশন",
        "best_sellers" to "সেরা বিক্রীত পণ্য",
        "view_all" to "সব দেখুন",
        "add_to_cart" to "কার্টে যোগ করুন",
        "buy_now" to "সরাসরি কিনুন",
        "in_stock" to "স্টকে আছে",
        "out_of_stock" to "স্টক শেষ",
        "stock_left" to "টি বাকি আছে",
        "reviews" to "রিভিউ ও রেটিং",
        "specifications" to "পণ্যের বিবরণ",
        "seller_info" to "বিক্রেতা",
        "delivery_free" to "৳১,০০০+ অর্ডারে ফ্রি হোম ডেলিভারি",
        "return_policy" to "৭ দিনের সহজ রিটার্ন পলিসি",
        "warranty" to "১০০% অরিজিনাল পণ্যের নিশ্চয়তা",
        "cart_title" to "শপিং কার্ট",
        "cart_empty" to "আপনার কার্ট খালি",
        "cart_empty_sub" to "আমাদের দারুণ অফার ও পণ্য ঘুরে দেখুন!",
        "start_shopping" to "কেনাকাটা শুরু করুন",
        "subtotal" to "সাবটোটাল",
        "discount" to "ছাড় (ডিসকাউন্ট)",
        "delivery_fee" to "ডেলিভারি চার্জ",
        "total" to "সর্বমোট মূল্য",
        "checkout" to "অর্ডার সম্পন্ন করতে এগিয়ে যান",
        "apply_coupon" to "কুপন কোড প্রয়োগ",
        "coupon_code" to "কুপন কোড লিখুন (যেমন: SIAM10)",
        "coupon_applied" to "কুপন সফলভাবে যুক্ত হয়েছে!",
        "coupon_invalid" to "কুপন কোডটি সঠিক নয়",
        "shipping_address" to "ডেলিভারি ঠিকানা",
        "select_address" to "ডেলিভারি ঠিকানা নির্বাচন করুন",
        "add_new_address" to "+ নতুন ঠিকানা যোগ করুন",
        "payment_method" to "পেমেন্ট মাধ্যম",
        "place_order" to "অর্ডার নিশ্চিত করুন",
        "order_success" to "আপনার অর্ডার সফলভাবে গৃহীত হয়েছে!",
        "order_success_sub" to "সিয়াম শপে কেনাকাটা করার জন্য ধন্যবাদ। আপনার অর্ডারটি লাইভ ট্র্যাক করতে পারবেন।",
        "order_tracking" to "অর্ডার ট্র্যাকিং",
        "order_history" to "পূর্ববর্তী অর্ডার সমূহ",
        "no_orders" to "কোনো অর্ডার পাওয়া যায়নি",
        "wishlist" to "পছন্দের তালিকা (উইশলিস্ট)",
        "wishlist_empty" to "আপনার পছন্দের তালিকা খালি",
        "notifications" to "নোটিফিকেশন",
        "profile" to "আমার প্রোফাইল",
        "switch_role" to "মোড পরিবর্তন করুন",
        "role_customer" to "কাস্টমার ভিউ",
        "role_seller" to "সেলার পার্টনার প্যানেল",
        "role_admin" to "অ্যাডমিন ড্যাশবোর্ড",
        "admin_dashboard" to "সিয়াম শপ অ্যাডমিন প্যানেল",
        "seller_dashboard" to "সেলার পার্টনার ড্যাশবোর্ড",
        "products_management" to "পণ্য ব্যবস্থাপনা",
        "categories_management" to "ক্যাটাগরি সমূহ",
        "orders_management" to "অর্ডার সমূহ",
        "coupons_management" to "কুপন ও অফার",
        "sellers_management" to "সেলার ব্যবস্থাপনা",
        "sales_report" to "বিক্রয় ও আয় রিপোর্ট",
        "banners_management" to "ব্যানার ও প্রমোশন",
        "total_revenue" to "মোট বিক্রয়",
        "total_orders" to "মোট অর্ডার",
        "active_sellers" to "সক্রিয় সেলার",
        "total_products" to "মোট পণ্য",
        "add_product" to "+ নতুন পণ্য যোগ করুন",
        "add_category" to "+ নতুন ক্যাটাগরি",
        "add_coupon" to "+ কুপন তৈরি করুন",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল",
        "delete" to "মুছুন",
        "edit" to "সম্পাদনা",
        "language_toggle" to "Language / ভাষা",
        "currency_symbol" to "৳",
        "taka" to "টাকা"
    )
}
